### ISSUE TITLE
'Map' object has no attribute 'bounds'

### ISSUE THREAD

**Issue by lincolnfrias** [ellisonbg/ipyleaflet#108]
m = Map(center = [34.62, -77.34])
    m.bounds 

gives:

> 'Map' object has no attribute 'bounds'

This is happening, for instance, in examples/Primitives.ipynb

Thanks for the awesomely useful and fun package :)

**Comment by SylvainCorlay** [comment]
Thanks for the report.
I have fixed the example notebook.
We have actually removed the `bounds` attribute. The reason is that multiple views of the same map may actually have different bounds. The only attributes for the location now are the center and the zoom level.

**Comment by SylvainCorlay** [comment]
Closing the issue. Don't hesitate to ask any question here should you have any!

**Comment by benjimin** [comment]
In the current master branch, the "primitives" notebook still refers to `.bounds` and `.bounds_polygon`.

**Comment by SylvainCorlay** [comment]
Thanks. I did not check in all the changes. Now it is all there.
