### ISSUE TITLE
map.bounds returning wrong bounding box

### ISSUE THREAD

**Issue by batic** [ellisonbg/ipyleaflet#121]
I have 
`m = Map(center=[-3.1, 37.4], zoom=10, layout=dict(width='1000px', height='400px'))`
and it displays correctly, but 
`m.bounds` report wrong bounding box:
`[(-3.3735983031347327, -3.3735983031347327),
 (-2.8250874941127346, 38.08685302734375)]`

Seems like a typo somewhere, as first coordinate is repeated twice.

**Comment by SylvainCorlay** [comment]
Right. It should be an easy fix. PR  welcome.

**Comment by SylvainCorlay** [comment]
Thx!

**Comment by SylvainCorlay** [comment]
@batic I just published a patch version with your fix.

**Comment by SylvainCorlay** [comment]
Now on conda-forge.
