### ISSUE TITLE
Vector layer should be always on top of raster/image layers

### ISSUE THREAD

**Issue by epifanio** [ellisonbg/ipyleaflet#28]
Adding a ``DrawControl()` to the map, and later on add a raster layer like:

```
io = ImageOverlay(url='http://ipython.org/_static/IPy_header.png', bounds=m.bounds)
m.add_layer(io)
```

When digitizing a new feature, the vector is drawn correctly, but behind the ImageOverlay.

**Comment by epifanio** [comment]
step to reproduce the behaviour:  https://gist.github.com/epifanio/6f9facdd177d39be85d912f092515b3c

**Comment by epifanio** [comment]
Any pointer on which part of the src code I should look into? I was looking at [jupyter-leaflet.js#L296](https://github.com/ellisonbg/ipyleaflet/blob/master/js/src/jupyter-leaflet.js#L296) trying  to understand if it is possible to  "reorder" the sequence of active layers, but I can't find any method to do that.

**Comment by ellisonbg** [comment]
Hmm, not sure how that could be accomplished and don't have time to dig into it right now :(

**Comment by SylvainCorlay** [comment]
Closing. Layers now always respect the order of the `layers` python tuple, and it cannot be altered by toggling the `visible` attribute anymore.
