### ISSUE TITLE
Downloading notebooks as html removes the leaflet outputs

### ISSUE THREAD

**Issue by aashrairavooru** [ellisonbg/ipyleaflet#36]
When I download my notebooks as html the leaflet outputs are always gone, same with downloading the notebook as ipynb or pdf

**Comment by SylvainCorlay** [comment]
@aashrairavooru the rendering as pdf is not supported. widgets can be rendered on static nbviewer if the notebook was saved with the widgets state, using the action in the `Widgets` menu of the notebook toolbar.
