### ISSUE TITLE
No Layer Control

### ISSUE THREAD

**Issue by Kevin-McIsaac** [ellisonbg/ipyleaflet#40]
Can anybody give advice on the following JS problem getting L.Control.Layer

Leaflet has a neat [Layer Control](http://leafletjs.com/examples/layers-control.html) that enables overlays (i.e., GroupLayers or GeoJSON layers) to be turned on on an off using a control. I created a [Python Class LayerControl](https://github.com/Kevin-McIsaac/ipyleaflet/tree/LayerControl), from the existing DrawingControl as a model. Unfortunately my code does not work and I don't have enough JS experience to figure out why.  

In a notebook I exercise my code by creating a map

```
from __future__ import print_function

from ipyleaflet import Map, Marker,TileLayer, LayerGroup, DrawControl, LayerControl
center = [34.6252978589571, -77.34580993652344]
zoom = 10
m = Map(center=center, zoom=zoom)
m

```

Then I create a LayerControl which I add to the map.

```
tile = TileLayer()
lg = LayerGroup(layers=[Marker(location=[m.south,  m.east], title="Hello"),
                        Marker(location=center, title="Hello", draggable=True)])
lc = LayerControl(base_layers = [tile],overlays = [lg] )
m.add_control(lc)

```

I get this browser console error.

```
leaflet-src.js:7958 Uncaught (in promise) TypeError: Cannot read property 'addTo' of undefined(…)addControl @ leaflet-src.js:7958

(anonymous function) @ jupyter-leaflet.js:388
```

My understanding is addTo is defined in the L.Control class that L.Control.Layer is extended from. So either the inheritance is not set up properly or my code is not creating a valid L.Control.Layer

**Comment by SylvainCorlay** [comment]
@Kevin-McIsaac closing this issue as a `LayerControl` widget was added to ipyleaflet with an example notebook.

**Comment by devdp** [comment]
LayerControl not working for more than one point. When ever I choose marker 1 it hides only one point out of 10 in marker1 as well as in marker2

**Comment by martinRenou** [comment]
Would you mind opening a specific issue for that? And provide some code to reproduce?

**Comment by devdp** [comment]
> @Kevin-McIsaac closing this issue as a `LayerControl` widget was added to ipyleaflet with an example notebook.

https://github.com/jupyter-widgets/ipyleaflet/issues/522#issue-584222641

please go through this link
