### ISSUE TITLE
Missing install step in docs?

### ISSUE THREAD

**Issue by psigen** [ellisonbg/ipyleaflet#45]
When installing and using this package with `jupyter` using the instructions from the README, I initially get the following error on OSX and Ubuntu (with fresh installations):

>Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"

Performing the extra step of running:
```
jupyter nbextension enable --py widgetsnbextension
```
seems to fix the problem.  I'm guessing that this is a dependency of `ipyleaflet` that needs similar registration the first time it is installed.  Perhaps it could be mentioned in the docs for new users?

**Comment by SylvainCorlay** [comment]
@psigen that is absolutely right!

**Comment by SylvainCorlay** [comment]
Fixed now that enabling extension is not required with notebook 5.4.
