### ISSUE TITLE
working in jupyter lab?

### ISSUE THREAD

**Issue by paul-shannon** [ellisonbg/ipyleaflet#46]
I have been tracking ipywidgets evolution, which are supposed to work with the evolving jupyter lab.  Figuring that ipyleaflet is exemplary - I have learned some tricks by studying your code -- I just tried to open GeoJSON.ipynb in  jupyter lab, after establishing that, as expected, it runs fine in the classic jupyter notebook.

I get this error: 

    Widget Javascript not detected.  It may not be installed or enabled properly.

accompanied by no other error messages or diagnostics.    Have you had any luck with yourwidget in the latest jupyter lab? 

None of my own widgets, all of which are working fine in the classic notebook, work in lab.  Emulating ipyleaflet might help me figure out what I need to do.

Thanks!

**Comment by SylvainCorlay** [comment]
@paul-shannon jupyter widgets in jupyterlab is still the bleeding edge.
While most of the work is done, installation is still quite cumbersome. I will post some instructions.

**Comment by paul-shannon** [comment]
@SylvainCorlay sorry to pester.   I'll be grateful for those instructions when you find the time...

**Comment by SylvainCorlay** [comment]
@paul-shannon no problem. 
 - So getting ipyleaflet to work in jupyterlab is quite cumbersome for now, since it requires installing ipywidgets from source and ipyleaflet from source
 - Besides, the jupyterlab team is iterating quite rapidly and makes rapid releases with non-backward compatible version numbers (`0.x.y`) before the first `1.0`.

Currently getting ipyleaflet in jupyterlab requires
 1.  `jupyterlab 0.11.3`. 
 2. The current state of master in ipywidgets
       -  In `jupyter-js=widgets`, run `npm install` 
       -  In `widgetsnbextension` , run `npm install` then `npm run update` then `pip install -e .`
       -  In `ipywidgets` run `pip install -e .`
       -  In `jupyterlab_widgets`  run `npm install` then `npm run update` then `pip install -e .`
       - `jupyter labextension install --py --sys-prefix --symlink jupyterlab_widgets`
       - `jupyter nbextension enable --py --sys-prefix jupyterlab_widgets`
 3. Install ipyleaflet from source
      - in `js`: npm install
      - at the root of the repo: `pip install -e .`
       - `jupyter labextension install --py --sys-prefix --symlink ipyleaflet`
       - `jupyter nbextension enable --py --sys-prefix jupyterlab_widgets`

yay!

**Comment by paul-shannon** [comment]
Many thanks @SylvainCorlay. 

All steps went smoothly:  thank you for laying them out.   

There's a good lesson for me in this:  despite your fine instructions, at the end of the process `jupyter lab --log-level=0` gets me only a blank screen in the browser, with no contents in the html body of that page.   I think I have come too early to jupyter lab development.  The "alpha preview" should have warned me away.

Thanks again for your (and Jason's) kindly and patiently offered help.  I will continue with ipywidget development in the notebook, returning to lab when the beta is released.

**Comment by epifanio** [comment]
Thanks  on (Gitter) , now we should be able to pip install `jupyterlab`,`notebook`, `ipywidgets`, and `ipyleaflet` (latest stable releases), and then `jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build` and then run `npm install && jupyter labextension install .` from the `ipyleaflets/jslab` folder. 
```
#!/usr/bin/env bash

npm install -g install bower
npm install typescript -g

pip3 install --upgrade pip
pip3 install jupyter
pip3 install notebook
pip3 install jupyterlab
pip3 install ipywidgets
pip3 install ipyleaflet


jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build

git clone https://github.com/ellisonbg/ipyleaflet
cd ipyleaflet/jslab
npm install && jupyter labextension install .
cd ../..

jupyter nbextension enable --py --sys-prefix ipyleaflet
```
Note: I used npm from their own PPA (on ubuntu 16.04, with the default system python 3.5)

**Comment by SylvainCorlay** [comment]
ipyleaflet now works in JupyterLab.

It can be installed by installing the pip package on the kernel side and running `jupyter labextension install jupyter-leaflet` for the lab extension.
