### ISSUE TITLE
How to figure out what password or token to use when trying mybinder setup

### ISSUE THREAD

**Issue by rdhyee** [ellisonbg/ipyleaflet#48]
When I go to http://mybinder.org/repo/ellisonbg/ipyleaflet/notebooks/examples, I'm prompted to enter a password or token.  What should I enter to use the notebooks on mybinder?

**Comment by rdhyee** [comment]
Just realized that a [proposed fix for mybinder](https://github.com/binder-project/binder-build-core/pull/10) is being discussed at https://gitter.im/binder-project/binder?at=587b8aeacbcb281770711932

**Comment by SylvainCorlay** [comment]
Thanks, closing since it seems that Jeremy has merged the fix. I will need to regenerate the binder.
