### ISSUE TITLE
Bing Maps and other TileLayers

### ISSUE THREAD

**Issue by updiversity** [ellisonbg/ipyleaflet#53]
Hi, 

there exist a Bing plugin for leaflet, that allows you to use the Bing Mapping Javascript API. 

At the moment, ipyleaflet (with the example provided), only provide as TileLayer an Openstreetmap one. 

Is there a way to use other tilelayers via ipyleaflet ?

**Comment by SylvainCorlay** [comment]
We can use a number of tile services in ipyleaflet. You can check out the BaseMap example notebook for a number of pre-registered tile layers!
