### ISSUE TITLE
JavaScript errors

### ISSUE THREAD

**Issue by DruidSmith** [ellisonbg/ipyleaflet#55]
Trying load a map from one of the simple examples in Jupyter and am getting the following:

tabbar.js:303 Uncaught Error: Script error for "jupyter-leaflet"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js?v=6da8be3…:165)
    at HTMLScriptElement.onScriptError (require.js?v=6da8be3…:1732)
makeError @ require.js?v=6da8be3…:165
onScriptError @ require.js?v=6da8be3…:1732

then this one twice:

tabbar.js:303 Uncaught Error: Script error for "jupyter-leaflet"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js?v=6da8be3…:165)
    at HTMLScriptElement.onScriptError (require.js?v=6da8be3…:1732)

**Comment by toolkids** [comment]
I'm not sure if this is the official solution. This was what I did and worked:

You could meet the following error when running ipyleaflet
Could not create model:
Model name  LeafletMapModel
Model module  jupyter-leaflet
Model module version  *
Script error for "jupyter-leaflet" http://requirejs.org/docs/errors.html...

**Solution 1:**
Keep the script page with errors open, and then create a new script page. Write your map drawing commands in the new page.

**Solution 2:**
In the page with error, type in the following script in one script cell:
!jupyter nbextension enable --py --sys-prefix ipyleaflet

Then, create a new script cell, and create a trial map:
Map(center=[32.7766, -96.7969], zoom=10)

Note that the Map function must be typed in a separate script cell. If you still see the error, keep the page with error open, and then create a new notebook script page to code.

**Comment by SylvainCorlay** [comment]
Thanks @toolkids this was the proper answer.

Indeed, the notebook extension was not properly enabled.

Quick note: as of notebook 5.4, ipyleaflet can be install with a simple `pip install` without having to enable the extension.
