### ISSUE TITLE
How to use different tile providers

### ISSUE THREAD

**Issue by dhirschfeld** [ellisonbg/ipyleaflet#56]
Just playing around with `ipyleaflet` - it's a neat project! I wasn't a big fan of the default OpenStreetMap tiles (too busy) so I figured out  how to use MapBox tiles.

In case it's of use for anyone else I've documented how to do so below. Since this isn't a real issue *per-se* feel free to close...

### Using Different Tile Providers
The underlying [leaflet.js](http://leafletjs.com/) library is provider agnostic and can be used with [almost](https://github.com/Leaflet/Leaflet/blob/master/FAQ.md#i-want-to-use-google-maps-api-tiles-with-leaflet-can-i-do-that) any tile provider. A preview of freely available tile providers is available at http://leaflet-extras.github.io/leaflet-providers/preview/.

[MapBox](https://www.mapbox.com/help/create-api-access-token/) is a tile provider which has a free plan which requires signing up to get an access token. To use MapBox (as with any other provider) you simply provide the correct url to the `TileLayer` constructor - e.g.
```python
url = "https://api.mapbox.com/v4/mapbox.outdoors/{z}/{x}/{y}.png?access_token=%s" % os.environ['MAPBOX_API_TOKEN']
provider = TileLayer(url=url, opacity=1)
m = Map(default_tiles=provider, center=(-27.4698, 153.0251), zoom=5)
m.layout.height = '800px'
m
```

**Comment by dhirschfeld** [comment]
xref #53

**Comment by mminin** [comment]
Is it possible to instantiate TileLayer.WMS object?
http://leafletjs.com/reference-1.1.0.html#tilelayer-wms

**Comment by fvivian** [comment]
> Is it possible to instantiate TileLayer.WMS object?
> http://leafletjs.com/reference-1.1.0.html#tilelayer-wms

I too would appreciate such a feature. I am trying to implement a WMS from Sinergise into a notebook. Not sure it this would help, though, but worth a shot.

**Comment by SylvainCorlay** [comment]
We can now instantiate a tile layer by providing the URL of an existing tile service, or use one of the pre-registered tile layers as shown in the BaseMap example notebook.

![strava-lab-view](https://user-images.githubusercontent.com/2397974/36567203-0738046c-1826-11e8-91fc-7ea355c6f4c9.gif)

**Comment by davidbrochart** [comment]
It doesn't seem to work with local tiles, with something like:
```python
l = {'url': 'file:///home/user/path/to/tiles/{z}/{x}/{y}.png'}
m.add_layer(l)
```
I get a `Not allowed to load local resource` in the browser debug console. I need to serve my tile directory with e.g.:
```bash
python -m http.server --bind 127.0.0.1
```
And change the URL to `http://127.0.0.1:8000/{z}/{x}/{y}.png`. But it would be nice if the Notebook could serve it.

**Comment by SylvainCorlay** [comment]
@davidbrochart thanks!

I would open a separate issue on serving local tile layers with the notebook server.

**Comment by davidbrochart** [comment]
Done in #257.

**Comment by SylvainCorlay** [comment]
Thanks!
