### ISSUE TITLE
Can't import ipyleaflet on any of my machines

### ISSUE THREAD

**Issue by jtaylor306** [ellisonbg/ipyleaflet#61]
Ran installation instructions as instructed on the docs(via conda). But I'm getting "cannot import Layout." On 4 different computers. Is this API still supported? 
``
from ipyleaflet import Map

Map(center=[34.6252978589571, -77.34580993652344], zoom=10)

``
![image](https://cloud.githubusercontent.com/assets/5560742/26597545/5aff2a3a-4540-11e7-91a4-98407fba75a6.png)

**Comment by toolkids** [comment]
Here are two commands that helped me. Hope they can help

**!pip install ipyleaflet
!jupyter nbextension enable --py --sys-prefix ipyleaflet**

A tutorial video can be found here [https://youtu.be/PuJ_JUkahXQ?t=14m1s](url)

**Comment by SylvainCorlay** [comment]
Thanks @toolkids for posting the video.

@jtaylor306 it seems that you have an old installation of ipywidgets. You may have installed an old version with `--user` .
