### ISSUE TITLE
MarkerCluster?

### ISSUE THREAD

**Issue by omrihar** [ellisonbg/ipyleaflet#63]
Hi there,

first of all, thanks for the great library! 

I'm wondering whether there is a way to use a Marker Cluster in `ipyleaflet`, such as is available in `folium` through the `folium.MarkerCluster`?

If not, I wouldn't mind trying to add this functionality and provide a PR, if I can get some pointers as to how to go about implementing it.

Thanks!
Omri

**Comment by rsignell-usgs** [comment]
Definitely would be useful!   :stuck_out_tongue_closed_eyes: 
![2017-11-12_19-04-23](https://user-images.githubusercontent.com/1872600/32704978-6eae1126-c7dc-11e7-94b0-a73187c8b9b1.png)

**Comment by jasongrout** [comment]
Fixed by #90.

**Comment by rsignell-usgs** [comment]
@omrihar , if you want to see how Jason did this enhancement, from conception to PR, check out this recording: https://www.youtube.com/watch?v=msJig1fr7Lw

**Comment by jasongrout** [comment]
This is released in ipyleaflet 0.5.3, which I just put up on pypi, and the conda-forge package is building at https://github.com/conda-forge/ipyleaflet-feedstock/pull/19

**Comment by omrihar** [comment]
@rsignell-usgs thanks! this video seems very informative and will definitely help get into understanding and developing nbextensions :) 
Once I have some time during the Christmas holidays I'll have a deeper look at it.
