### ISSUE TITLE
Cannot set output cell size with Map() height/width params

### ISSUE THREAD

**Issue by mxndrwgrdnr** [ellisonbg/ipyleaflet#64]
Perhaps related to #57, but the `height` and `width` params of the `Map()` class do not alter the output size whatsoever.

**Comment by SylvainCorlay** [comment]
@mxndrwgrdnr you can use the `layout` attribute of the widget.

Here is the relevant section of the documentation: http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html

**Comment by mxndrwgrdnr** [comment]
Perfect. Thank you.

**Comment by dietmar** [comment]
To make it more explicit for those who come here via web search (like me).

You can assign CSS sizes like this:

```
m = Map()
m.layout.width = '50%'
m.layout.height = '300px'
m
```

**Comment by orian** [comment]
I do define a default layout like this:

```
from ipywidgets import Layout
defaultLayout=Layout(width='960px', height='540px')

m = Map(center=[51.83577752045248, 19.544677734375004], zoom=6, layout=defaultLayout)
m
```
