### ISSUE TITLE
Adding layers fails with ipywidgets 7.0

### ISSUE THREAD

**Issue by SylvainCorlay** [ellisonbg/ipyleaflet#67]
Displaying basic maps works fine with the update to ipywidgets 7.0, but additional layers are not being displayed.

**Comment by stonebig** [comment]
any news on this ? did you try with ipyleafet-0.4.0a1 ?

**Comment by jasongrout** [comment]
@ssunkara1 has tracked down a problem with adding layers. Apparently it has to do with a styling issue, and the new layer is a 0x0 div, or something like that. I'll let him elaborate.

**Comment by stonebig** [comment]
for me it works with Ipyleaflet-0.4.0 (in the Notebook-5.1.0rc2)

**Comment by jasongrout** [comment]
Great, thanks for confirming! @ssunkara1 said the updated leaflet solved the issue for him. Closing.
