### ISSUE TITLE
error trying ipyleaflet-0.4.0

### ISSUE THREAD

**Issue by stonebig** [ellisonbg/ipyleaflet#75]
I get this error that I don't undertand (on  Windows/Winpython):
````
Disabling terminals plugin because they are not available on the server
main.bundle.js:170990 Starting WebSocket: ws://localhost:8888/api/kernels/7e61aa74-e3f6-4fa0-804d-fc09c2dae816
main.bundle.js:171758 Kernel: connected (7e61aa74-e3f6-4fa0-804d-fc09c2dae816)
main.bundle.js:148306 Could not instantiate widget
(anonymous) @ main.bundle.js:148306
main.bundle.js:49724 Error: Could not create a model.
    at promiseRejection (main.bundle.js:49724)
    at <anonymous>
promiseRejection @ main.bundle.js:49724
main.bundle.js:148306 Could not instantiate widget
(anonymous) @ main.bundle.js:148306
main.bundle.js:49724 Error: Could not create a model.
    at promiseRejection (main.bundle.js:49724)
    at <anonymous>
promiseRejection @ main.bundle.js:49724
main.bundle.js:148306 Could not instantiate widget
(anonymous) @ main.bundle.js:148306
main.bundle.js:49724 Error: Could not create a model.
    at promiseRejection (main.bundle.js:49724)
    at <anonymous>
promiseRejection @ main.bundle.js:49724
main.bundle.js:148306 Could not instantiate widget
(anonymous) @ main.bundle.js:148306
main.bundle.js:49724 Error: Could not create a model.
    at promiseRejection (main.bundle.js:49724)
    at <anonymous>
promiseRejection @ main.bundle.js:49724
main.bundle.js:153773 Error displaying widget
main.bundle.js:153774 Module jupyter-leaflet, semver range 0.4.0 is not registered as a widget module
lab:1 Uncaught (in promise) Module jupyter-leaflet, semver range 0.4.0 is not registered as a widget module
````
What may I check ?

**Comment by stonebig** [comment]
it's on Jupyterlab-0.27.0, on Jupyter Notebook, overlay issue is solved. thanks

**Comment by jasongrout** [comment]
1. How did you install things?

2. Are you seeing a map?

The error indicates that the jupyterlab extension is not installed.

**Comment by stonebig** [comment]
I see nothing. maybe I miss a step. was "jupyter nbextension enable --py --sys-prefix ipyleaflet" sufficient ?

**Comment by jasongrout** [comment]
You'll need to install the jupyterlab extension to have it working in jupyterlab. This extension is not published on npm yet, but you can install it from the git repo: `jupyter labextension install ./jslab`

**Comment by stonebig** [comment]
I don't see where it is.... will just wait for simpler times

**Comment by jasongrout** [comment]
@ellisonbg - perhaps the jlab package should be published to npm. Any preference on the name and/or namespace?

**Comment by stonebig** [comment]
hope ?

**Comment by tylere** [comment]
+1 to publishing it on npm.

**Comment by tylere** [comment]
@stonebig the following worked for me:

```
git clone https://github.com/ellisonbg/ipyleaflet.git
jupyter labextension install ipyleaflet/jslab
```

**Comment by stonebig** [comment]
thanks, @tylere. I will have a look at this workaround for my next try.

**Comment by stonebig** [comment]
@tylere awesome, thanks !

**Comment by tylere** [comment]
Installing `ipyleaflet/jslab` no longer works for me. I see that @jasongrout recently posted [jupyter-leaflet](https://www.npmjs.com/package/jupyter-leaflet) to npm. Is there a revised set of commands for getting ipyleaflet to work in jupyterlab?

Installation details with error are below.

<details>
    <summary>docker build output</summary>

    Sending build context to Docker daemon  58.37kB
    Step 1/7 : FROM jupyter/scipy-notebook
     ---> a541a282ff6a
    Step 2/7 : MAINTAINER Tyler Erickson <tylere@google.com>
     ---> Using cache
     ---> bf7aee1d2cd5
    Step 3/7 : USER root
     ---> Using cache
     ---> ce153c9ac305
    Step 4/7 : RUN apt-get update   && apt-get install -y --no-install-recommends              libjpeg-dev              libgif-dev              libcairo2-dev              pkg-config   && pip install ipywidgets   && jupyter nbextension enable --py widgetsnbextension --sys-prefix   && jupyter labextension install @jupyter-widgets/jupyterlab-manager   && pip install ipyleaflet   && jupyter nbextension enable --py --sys-prefix ipyleaflet   && apt-get install -y --no-install-recommends              build-essential              libssl-dev              libffi-dev   && pip install cryptography   && apt-get purge -y build-essential              libssl-dev              libffi-dev              dpkg-dev              pkg-config              fakeroot              libfakeroot:amd64   && apt-get autoremove -y   && apt-get clean   && rm -rf /var/lib/apt/lists/*
     ---> Using cache
     ---> c761fd0448e1
    Step 5/7 : RUN git clone https://github.com/ellisonbg/ipyleaflet.git   && jupyter labextension install ipyleaflet/jslab   && rm -fr ipyleaflet
     ---> Running in 5d454cff8912
    Cloning into 'ipyleaflet'...
    > npm pack ipyleaflet/jslab
    npm ERR! git clone --template=/home/jovyan/.npm/_git-remotes/_templates --mirror git@github.com:ipyleaflet/jslab.git /home/jovyan/.npm/_git-remotes/git-github-com-ipyleaflet-jslab-git-f4a7fdd3: Cloning into bare repository '/home/jovyan/.npm/_git-remotes/git-github-com-ipyleaflet-jslab-git-f4a7fdd3'...
    npm ERR! git clone --template=/home/jovyan/.npm/_git-remotes/_templates --mirror git@github.com:ipyleaflet/jslab.git /home/jovyan/.npm/_git-remotes/git-github-com-ipyleaflet-jslab-git-f4a7fdd3: error: cannot run ssh: No such file or directory
    npm ERR! git clone --template=/home/jovyan/.npm/_git-remotes/_templates --mirror git@github.com:ipyleaflet/jslab.git /home/jovyan/.npm/_git-remotes/git-github-com-ipyleaflet-jslab-git-f4a7fdd3: fatal: unable to fork
    npm ERR! Linux 4.9.49-moby
    npm ERR! argv "/opt/conda/bin/node" "/opt/conda/bin/npm" "pack" "ipyleaflet/jslab"
    npm ERR! node v6.11.0
    npm ERR! npm  v3.10.10
    npm ERR! code 128

    npm ERR! Command failed: git clone --template=/home/jovyan/.npm/_git-remotes/_templates --mirror git@github.com:ipyleaflet/jslab.git /home/jovyan/.npm/_git-remotes/git-github-com-ipyleaflet-jslab-git-f4a7fdd3
    npm ERR! Cloning into bare repository '/home/jovyan/.npm/_git-remotes/git-github-com-ipyleaflet-jslab-git-f4a7fdd3'...
    npm ERR! error: cannot run ssh: No such file or directory
    npm ERR! fatal: unable to fork
    npm ERR! 
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /opt/conda/share/jupyter/lab/extensions/temp/npm-debug.log
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/tarfile.py", line 1640, in gzopen
        t = cls.taropen(name, mode, fileobj, **kwargs)
      File "/opt/conda/lib/python3.6/tarfile.py", line 1616, in taropen
        return cls(name, mode, fileobj, **kwargs)
      File "/opt/conda/lib/python3.6/tarfile.py", line 1479, in __init__
        self.firstmember = self.next()
      File "/opt/conda/lib/python3.6/tarfile.py", line 2294, in next
        tarinfo = self.tarinfo.fromtarfile(self)
      File "/opt/conda/lib/python3.6/tarfile.py", line 1089, in fromtarfile
        buf = tarfile.fileobj.read(BLOCKSIZE)
      File "/opt/conda/lib/python3.6/gzip.py", line 276, in read
        return self._buffer.read(size)
      File "/opt/conda/lib/python3.6/_compression.py", line 68, in readinto
        data = self.read(len(byte_view))
      File "/opt/conda/lib/python3.6/gzip.py", line 463, in read
        if not self._read_gzip_header():
      File "/opt/conda/lib/python3.6/gzip.py", line 411, in _read_gzip_header
        raise OSError('Not a gzipped file (%r)' % magic)
    OSError: Not a gzipped file (b'0 ')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/bin/jupyter-labextension", line 6, in <module>
        sys.exit(jupyterlab.labextensions.main())
      File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
        app.start()
      File "/opt/conda/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 168, in start
        super(LabExtensionApp, self).start()
      File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
        self.subapp.start()
      File "/opt/conda/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 58, in start
        for arg in self.extra_args]
      File "/opt/conda/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 58, in <listcomp>
        for arg in self.extra_args]
      File "/opt/conda/lib/python3.6/site-packages/jupyterlab/commands.py", line 127, in install_extension
        return IOLoop.instance().run_sync(func)
      File "/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
        return future_cell[0].result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "/opt/conda/lib/python3.6/site-packages/jupyterlab/commands.py", line 172, in install_extension_async
        data = _read_package(pjoin(target, fname))
      File "/opt/conda/lib/python3.6/site-packages/jupyterlab/commands.py", line 1019, in _read_package
        tar = tarfile.open(target, "r:gz")
      File "/opt/conda/lib/python3.6/tarfile.py", line 1586, in open
        return func(name, filemode, fileobj, **kwargs)
      File "/opt/conda/lib/python3.6/tarfile.py", line 1644, in gzopen
        raise ReadError("not a gzip file")
    tarfile.ReadError: not a gzip file
    The command '/bin/sh -c git clone https://github.com/ellisonbg/ipyleaflet.git   && jupyter labextension install ipyleaflet/jslab   && rm -fr ipyleaflet' returned a non-zero code: 1
</details>

**Comment by jasongrout** [comment]
Yes, we've combined the js packages and published the result. Now it is just `jupyter labextension install jupyter-leaflet`.

In the next revision, we may even be able to dispense with even that - and install the jlab plugin automatically when you install the python package.

**Comment by jasongrout** [comment]
I've added jlab installation instructions to the readme: #82.

**Comment by davidbrochart** [comment]
I'm not sure it's related, but the development installation mode doesn't work anymore for me. When I follow the instructions in the README (after `jupyter labextension install jupyter-leaflet`), it always takes the published package.

**Comment by SylvainCorlay** [comment]
@DavidBrochart actually what you are describing is the expected behavior. Lab extension fetch the js assets from npm.

To install the lab extension from source, you need to specify a directory instead.
