### ISSUE TITLE
Uncaught Error: Script error for "@jupyter-widgets/base"

### ISSUE THREAD

**Issue by mjurowicz-xsolve** [ellisonbg/ipyleaflet#76]
The embedded version of ipyleaflet is broken. It does not work in nbviewer and in the `http://jupyter.org/widgets.html`
It throws the: `Uncaught Error: Script error for "@jupyter-widgets/base", needed by: https://unpkg.com/jupyter-leaflet@*/dist/index.js`.

the problem is the `module_name` that is resolved to `@jupyter-widgets/base` instead of the `jupyter-js-widgets` as the ipywidgets are available under the `jupyter-js-widgets` name by requirejs on `nbviewer` and `http://jupyter.org/widgets.html`

**Comment by scottdraves** [comment]
maybe not jason says:
> I think the issue is that page tries to use the most recent version of ipyleaflet (the * in the request indicates it's trying to get the most recent version), but the data has not been updated and is only compatible with a previous version

**Comment by jasongrout** [comment]
The switch from jupyter-js-widgets to `@jupyter-widgets/base` happened in ipywidgets 7. nbviewer needs to be upgraded to handle ipywidgets 7 - it's hardcoded at ipywidgets 6. We're tracking that at https://github.com/jupyter/nbviewer/issues/717

For the jupyter.org webpage, it's also hardcoded at ipywidgets 6: https://github.com/jupyter/jupyter.github.io/blob/fae454d82f28cf98ce0d1cc4cd1eec59a4a3fe45/widgets.html#L8. However, the code tries to load the ipywidgets 7 version of ipyleaflet. The quick fix is to only load the ipywidgets 6 version of ipyleaflet. The more permanent fix is to upgrade the website code to use ipywidgets 7.

**Comment by jasongrout** [comment]
> The quick fix is to only load the ipywidgets 6 version of ipyleaflet.

On second thought, it may not be that easy - I think loading the latest version is hardcoded in that embedding javascript. It's probably best to switch it to use ipywidgets 7, using instructions at http://ipywidgets.readthedocs.io/en/stable/migration_guides.html#updating-embedded-widgets and updating the json data file with a version from the latest ipywidgets release.

**Comment by jasongrout** [comment]
Regardless, though, this is an issue with the Jupyter web page, not ipyleaflet.

**Comment by jasongrout** [comment]
I opened https://github.com/jupyter/jupyter.github.io/issues/240 to track the update to the webpage. With those two issues tracking these things, I'll close this one.
