### ISSUE TITLE
New View for cell containing ipyleaflet map has issues displaying tiles

### ISSUE THREAD

**Issue by tylere** [ellisonbg/ipyleaflet#84]
In JupyterLab, after clicking "Create New View for Cell" on an ipyleaflet map, the new view seems to have a different center coordinates, and tiles fail to appear. 

![image](https://user-images.githubusercontent.com/92862/32877438-623c8054-ca56-11e7-89f6-b5588b75699a.png)

Note that the tile(s) shown in the upper left of the new view map are the same ones shown in the  lower right of the original map cell.  i.e. the missing tiles would be visible in the new map view if the center coordinates were correct.

My current setup:
jupyter_core.__version__ = 4.4.0
jupyter_client.__version__ = 5.1.0
jupyterlab.__version__ = 0.29.1
jupyterlab_launcher.__version__ = 0.5.5
ipyleaflet.__version__ = 0.5.1

**Comment by SylvainCorlay** [comment]
@tylere this is now fixed in the recent releases.

Also, the new view for the map will occupy all the available space in the mirrored output!

**Comment by tylere** [comment]
@SylvainCorlay it seems to work great. Thanks!
