### ISSUE TITLE
No map and "Could not create model"

### ISSUE THREAD

**Issue by kannes** [ellisonbg/ipyleaflet#85]
If you get a non-descript error like

```
Could not create model:
Model name 	LeafletMapModel
Model module 	jupyter-leaflet
Model module version 	*
Script error for "jupyter-leaflet" http://requirejs.org/docs/errors.html#scripterror 
```

after enabling ipyleaflet and trying to display a map in a notebook, upgrade ipyleaflet (via pip or whatever you use). In my case I seem to have had some version mismatches. Sadly that was the only error message and it was not helpful at all

**Comment by Ocuatrec** [comment]
Did you ever solve your error?

**Comment by kannes** [comment]
> upgrade ipyleaflet (via pip or whatever you use)

solved it for me?
