### ISSUE TITLE
Upgraded to 0.5.3, and marker is working, but not markerCluster

### ISSUE THREAD

**Issue by rsignell-usgs** [ellisonbg/ipyleaflet#91]
I upgraded to 0.5.3, and `Marker`is working, but not `MarkerCluster`.   I just get a blank map.

**Comment by rsignell-usgs** [comment]
Ah, in developer tools, I see that even though the version is showing at 0.5.3, the javascript can't find markercluster.

**Comment by rsignell-usgs** [comment]
Okay, figured this out. 

I'm running on Windows, and firing up `jupyter notebook` from my base Conda environment, then running the notebook in a custom `widgets` environment that had the upgraded `ipyleaflet`.   

When I upgraded my base environment to the latest version of `ipyleaflet`, and restarted `jupyter notebook`, the notebook worked fine in my `widgets` environment.

So I guess the python side was using my custom kernel, but the JS side was using my base environment.  Does that sound right?

**Comment by jasongrout** [comment]
> So I guess the python side was using my custom kernel, but the JS side was using my base environment. Does that sound right?

Yes.

**Comment by rsignell-usgs** [comment]
Is this described in widgets doc somewhere?   I probably just missed it.

**Comment by jasongrout** [comment]
Good question. It comes up often enough that we should have a troubleshooting FAQ with things like this in it.
